Plugin 'gmarik/vundle'
Plugin 'tpope/vim-sensible'
Plugin 'mkropat/vim-dwiw2015'
Plugin 'bling/vim-airline'
Plugin 'kien/ctrlp.vim'
Plugin 'rking/ag.vim'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-sleuth'
