# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/opt/llvm/bin:/usr/local/bin:/usr/local/sbin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="bullet-train"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=$HOME/.zsh-custom

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git wd globalias
  #asdf
)

if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi

# while [ -z "$(ls -A $HOME/.dotfiles/sensitive)" ]
# do
#     clear
#     if [[ "$WINDOW" == '1' ]]
#     then
#         (cd $HOME/.dotfiles && make)
#         clear
#     else
#         sleep 1
#     fi
# done

source $ZSH/oh-my-zsh.sh

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

autoload -U zsh-mime-setup
zsh-mime-setup

setopt nosharehistory
setopt autocd

# Disable software flow control
stty -ixon

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
prompt_context() {}

export KEYTIMEOUT=1

bindkey "^R" history-incremental-search-backward

bindkey -M emacs " " magic-space
bindkey -M viins " " magic-space
bindkey -M emacs "^E" globalias
bindkey -M viins "^E" globalias
bindkey -s "^\\" "fg\n"

export PYTHONSTARTUP=~/.pythonrc.py
export PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs4 --enable-shared"
export MACOSX_DEPLOYMENT_TARGET="10.15"
export XMODIFIERS=''
export EDITOR=nvim
export BULLETTRAIN_VIRTUALENV_SHOW=false
export BULLETTRAIN_RUBY_SHOW=false
export BULLETTRAIN_TIME_SHOW=false
export PYTEST_ADDOPTS="-s"
unset LSCOLORS

setopt NO_HUP
setopt NO_CHECK_JOBS

#export TZ="America/Sao_Paulo"
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

# if [ -f ~/.asdf/plugins/java/set-java-home.sh ]
# then
#   source ~/.asdf/plugins/java/set-java-home.sh
# fi

# if [ -e /Users/rodrigo/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/rodrigo/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
eval "$(direnv hook zsh)"

# Created by `userpath` on 2020-11-21 14:34:46
export PATH="$PATH:/Users/rodrigo/.local/bin"
export PATH="$PATH:/opt/homebrew/bin"
export PATH="$PATH:/Applications/IntelliJ IDEA CE.app/Contents/MacOS"

alias ls="ls --color"
alias vim="nvim"
alias vi="nvim"
alias oldvim="\vim"
export DISABLE_AUTO_TITLE='true'
# [ ! -n "$TMUX" ] && while true; do tmuxp load -y default; done
